[package]
name = "rust-rayon-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
geo = "0.28.0"
geojson = "0.24.1"
rayon = "1.10.0"
